export default [
	{
		title: "Shivam Portfolio",
		img: "https://github.com/aslezar/ShareSketch/raw/main/resources/Homepage.png",
		techStack: ["Tailwind CSS", "React", "Javascript", "HTML", "CSS"],
		time_from: "Jan 2024",
		time_to: "Feb 2024",
		description:
			"This is my portfolio website. It is a resume converted into website.",
		liveDemo: "https://github.com/aslezar",
		githubRepo: "https://github.com/aslezar/aslezar",
	},
	{
		title: "ShareSketch",
		img: "https://github.com/aslezar/ShareSketch/raw/main/resources/Homepage.png",
		techStack: [
			"React",
			"Javascript",
			"HTML",
			"CSS",
			"Socket.io",
			"MongoDB",
			"NodeJS",
			"ExpressJS",
		],
		time_from: "Aug 2023",
		time_to: "Sept 2023",
		description:
			"Sharesketch is a collaborative real time whiteboad sharing website.",
		liveDemo: "https://github.com/aslezar",
		githubRepo: "https://github.com/aslezar/aslezar",
	},
	{
		title: "Shivam Portfolio",
		img: "https://github.com/aslezar/ShareSketch/raw/main/resources/Homepage.png",
		techStack: [
			"React",
			"Javascript",
			"HTML",
			"CSS",
			"Socket.io",
			"MongoDB",
			"NodeJS",
			"ExpressJS",
		],
		time_from: "Mar 2024",
		time_to: "May 2024",
		description:
			"This is my portfolio website. It is a resume converted into website.",
		liveDemo: "https://github.com/aslezar",
		githubRepo: "https://github.com/aslezar/aslezar",
	},
	{
		title: "Shivam Portfolio",
		img: "https://github.com/aslezar/ShareSketch/raw/main/resources/Homepage.png",
		techStack: [
			"React",
			"Javascript",
			"HTML",
			"CSS",
			"Socket.io",
			"MongoDB",
			"NodeJS",
			"ExpressJS",
		],
		time_from: "Mar 2024",
		time_to: "May 2024",
		description:
			"This is my portfolio website. It is a resume converted into website.",
		liveDemo: "https://github.com/aslezar",
		githubRepo: "https://github.com/aslezar/aslezar",
	},
];
